
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/dev/msys/ucrt64/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
